require 'simplecov'
SimpleCov.start
require 'minitest/autorun'
require 'minitest/pride'
require 'mocha/minitest'
require './lib/key_generator'
require './lib/offset_generator'
require './lib/shift'
require './lib/enigma'
require './lib/messenger'
